version: "3.7"
services:
  ########################################
  #  #plex - media server
  ########################################
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /mnt/storage/appdata/plex:/config
      - /mnt/storage/media/tv:/data/tvshows
      - /mnt/storage/media/home_movies:/data/home_movies
      - /mnt/storage/media/photos:/data/photos
      - /mnt/storage/media/movies:/data/movies
      - /mnt/storage/media/christmas:/data/christmas
      - /mnt/storage/media/kids:/data/kids
      - /mnt/storage/media/4kmovies:/data/4kmovies
      - /mnt/storage/media/music:/data/music
      - /mnt/storage/tmp:/transcode
      - /mnt/storage/appdata/docker/shared:/shared
    # network_mode: host
    networks:
      priv_lan:
        ipv4_address: 10.0.0.12
    restart: always
    ports:
      - 32400:32400/tcp
#      - 3005:3005/tcp
#      - 8324:8324/tcp
#      - 32469:32469/tcp
     # - 1900:1900/udp
#      - 32410:32410/udp
#      - 32412:32412/udp
#      - 32413:32413/udp
#      - 32414:32414/udp
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ADVERTISE_IP="http://10.0.0.12:32400/"
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ALLOWED_NETWORKS=10.0.0.0/8

  cloudflared:
    container_name: cloudflared
    # Restart on crashes and on reboots
    restart: unless-stopped
    image: cloudflare/cloudflared
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query"

      # Listen on an unprivileged port
      - "TUNNEL_DNS_PORT=5053"

      # Listen on all interfaces
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"

    # Attach cloudflared only to the private network
    networks:
      internal:
        ipv4_address: 172.30.9.2

  pihole:
    container_name: pihole
    restart: unless-stopped
    image: pihole/pihole
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=admin"

      # Internal IP of the cloudflared container
      - "DNS1=172.30.9.2#5053"

      # Explicitly disable a second DNS server, otherwise Pi-hole uses Google
      - "DNS2=no"
      - "DNSMASQ_LISTENING=all"

    # Persist data and custom configuration to the host's storage
    volumes:
      - /mnt/storage/appdata/pihole/config:/etc/pihole/
      - /mnt/storage/appdata/pihole/dnsmasq:/etc/dnsmasq.d/
    networks:
      internal:
        ipv4_address: 172.30.9.3
      priv_lan:
        ipv4_address: 10.0.0.11
    depends_on:
      - cloudflared
networks:
  internal:
    ipam:
      config:
        - subnet: 172.30.9.0/29
  priv_lan:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 10.0.0.0/16
  #         gateway: 10.0.0.1
