apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mopidy
  name: mopidy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mopidy
    spec:
      containers:
      - image: wernight/mopidy
        name: mopidy
        ports:
        - containerPort: 6600
        - containerPort: 6680
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mopidy/local
          name: mopidy-claim0
      restartPolicy: Always
      volumes:
      - name: mopidy-claim0
        persistentVolumeClaim:
          claimName: mopidy-claim0
status: {}
