apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: mylar
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.auth.basic.users: tdelesio:$apr1$MB/owCuq$Wk7GuIG6a/TByQEeT5yN9.
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:mylar.delesio.com
    traefik.port: "8090"
  creationTimestamp: null
  labels:
    io.kompose.service: mylar
  name: mylar
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mylar
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
          value: '"America/New_York"'
        image: linuxserver/mylar
        name: mylar
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: mylar-claim0
        - mountPath: /downloads
          name: htpmanager-complete-downloads
        - mountPath: /comics
          name: htpmanager-comics
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: mylar-claim0
        persistentVolumeClaim:
          claimName: mylar-claim0
      - name: htpmanager-complete-downloads
        persistentVolumeClaim:
          claimName: htpmanager-complete-downloads
      - name: htpmanager-comics
        persistentVolumeClaim:
          claimName: htpmanager-comics
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
