apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: netdata
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.auth.basic.users: tdelesio:$apr1$MB/owCuq$Wk7GuIG6a/TByQEeT5yN9.
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:netdata.delesio.com
    traefik.port: "19999"
  creationTimestamp: null
  labels:
    io.kompose.service: netdata
  name: netdata
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: netdata
    spec:
      containers:
      - image: netdata/netdata
        name: netdata
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        volumeMounts:
        - mountPath: /host/proc
          name: netdata-claim0
          readOnly: true
        - mountPath: /host/sys
          name: netdata-claim1
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: netdata-claim2
          readOnly: true
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: netdata-claim0
        persistentVolumeClaim:
          claimName: netdata-claim0
          readOnly: true
      - name: netdata-claim1
        persistentVolumeClaim:
          claimName: netdata-claim1
          readOnly: true
      - name: netdata-claim2
        persistentVolumeClaim:
          claimName: netdata-claim2
          readOnly: true
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
