apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: hydra
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:hydra.delesio.com
    traefik.port: "5075"
  creationTimestamp: null
  labels:
    io.kompose.service: nzbhydra
  name: nzbhydra
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nzbhydra
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: 'TZ '
          value: ' "America/New_York"'
        image: linuxserver/hydra
        name: hydra
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: nzbhydra-claim0
        - mountPath: /downloads
          name: htpmanager-complete-downloads
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: nzbhydra-claim0
        persistentVolumeClaim:
          claimName: nzbhydra-claim0
      - name: htpmanager-complete-downloads
        persistentVolumeClaim:
          claimName: htpmanager-complete-downloads
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
