apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: phlex
  name: phlex
spec:
  ports:
  - name: "5666"
    port: 5666
    targetPort: 80
  - name: "5667"
    port: 5667
    targetPort: 443
  selector:
    io.kompose.service: phlex
status:
  loadBalancer: {}
