apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: plex
    spec:
      containers:
      - env:
        - name: ADVERTISE_IP
          value: '"http://10.0.0.10:32400/"'
        - name: ALLOWED_NETWORKS
          value: 10.0.0.0/8
        - name: HOSTNAME
          value: '"Docker Plex"'
        - name: PGID
        - name: PLEX_CLAIM
          value: claim-1Zg5Z3bz213LqvmFYWab
        - name: PUID
        - name: TZ
          value: '"America/New_York"'
        - name: VERSION
          value: public
        image: linuxserver/plex
        name: plex
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: plex-claim0
        - mountPath: /data/tvshows
          name: htpmanager-tv
        - mountPath: /data/homemovies
          name: htpmanager-home-movies
        - mountPath: /data/photos
          name: htpmanager-photos
        - mountPath: /data/movies
          name: htpmanager-movies
        - mountPath: /data/christmas
          name: htpmanager-christmas-movies
        - mountPath: /data/kids
          name: htpmanager-kids-movies
        - mountPath: /data/music
          name: htpmanager-music
        - mountPath: /transcode
          name: htpmanager-temp-storage
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: plex-claim0
        persistentVolumeClaim:
          claimName: plex-claim0
      - name: htpmanager-tv
        persistentVolumeClaim:
          claimName: htpmanager-tv
      - name: htpmanager-home-movies
        persistentVolumeClaim:
          claimName: htpmanager-home-movies
      - name: htpmanager-photos
        persistentVolumeClaim:
          claimName: htpmanager-photos
      - name: htpmanager-movies
        persistentVolumeClaim:
          claimName: htpmanager-movies
      - name: htpmanager-christmas-movies
        persistentVolumeClaim:
          claimName: htpmanager-christmas-movies
      - name: htpmanager-kids-movies
        persistentVolumeClaim:
          claimName: htpmanager-kids-movies
      - name: htpmanager-music
        persistentVolumeClaim:
          claimName: htpmanager-music
      - name: htpmanager-temp-storage
        persistentVolumeClaim:
          claimName: htpmanager-temp-storage
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
