apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: sabnzbd
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:downloads.delesio.com
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: sabnzbd
  name: sabnzbd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sabnzbd
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
          value: '"America/New_York"'
        image: linuxserver/sabnzbd
        name: sabnzbd
        resources: {}
        volumeMounts:
        - mountPath: /comics
          name: htpmanager-comics
        - mountPath: /config
          name: sabnzbd-claim1
        - mountPath: /config/Downloads
          name: htpmanager-complete-downloads
        - mountPath: /config/incomplete
          name: htpmanager-incomplete-downloads
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: htpmanager-comics
        persistentVolumeClaim:
          claimName: htpmanager-comics
      - name: sabnzbd-claim1
        persistentVolumeClaim:
          claimName: sabnzbd-claim1
      - name: htpmanager-complete-downloads
        persistentVolumeClaim:
          claimName: htpmanager-complete-downloads
      - name: htpmanager-incomplete-downloads
        persistentVolumeClaim:
          claimName: htpmanager-incomplete-downloads
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
