apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: sonarr
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.auth.basic.users: tdelesio:$apr1$MB/owCuq$Wk7GuIG6a/TByQEeT5yN9.
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:sonarr.delesio.com
    traefik.port: "8989"
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
          value: '"America/New_York"'
        image: linuxserver/sonarr
        name: sonarr
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: sonarr-claim0
        - mountPath: /tv
          name: htpmanager-tv
        - mountPath: /config/Downloads
          name: htpmanager-complete-downloads
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: sonarr-claim0
        persistentVolumeClaim:
          claimName: sonarr-claim0
      - name: htpmanager-tv
        persistentVolumeClaim:
          claimName: htpmanager-tv
      - name: htpmanager-complete-downloads
        persistentVolumeClaim:
          claimName: htpmanager-complete-downloads
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
