apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: tautulli
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:stats.delesio.com
    traefik.port: "8181"
  creationTimestamp: null
  labels:
    io.kompose.service: tautulli
  name: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tautulli
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
          value: '"America/New_York"'
        image: linuxserver/tautulli
        name: tautulli
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: tautulli-claim0
        - mountPath: /logs
          name: tautulli-claim1
          readOnly: true
        - mountPath: /shared
          name: htpmanager-shared
      restartPolicy: Always
      volumes:
      - name: tautulli-claim0
        persistentVolumeClaim:
          claimName: tautulli-claim0
      - name: tautulli-claim1
        persistentVolumeClaim:
          claimName: tautulli-claim1
          readOnly: true
      - name: htpmanager-shared
        persistentVolumeClaim:
          claimName: htpmanager-shared
status: {}
