apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
    traefik.backend: traefik
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.auth.basic.users: tdelesio:$apr1$MB/owCuq$Wk7GuIG6a/TByQEeT5yN9.
    traefik.frontend.headers.SSLHost: delesio.com
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "true"
    traefik.frontend.rule: Host:traefik.delesio.com
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - env:
        - name: CF_API_EMAIL
          value: tdelesio@gmail.com
        - name: CF_API_KEY
          value: 51cdc975903470f25267d0dd817eddc3fa572
        image: traefik:latest
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: traefik-claim0
          readOnly: true
        - mountPath: /etc/traefik
          name: traefik-claim1
        - mountPath: /shared
          name: traefik-claim2
      hostname: traefik
      restartPolicy: Always
      subdomain: delesio.com
      volumes:
      - name: traefik-claim0
        persistentVolumeClaim:
          claimName: traefik-claim0
          readOnly: true
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
      - name: traefik-claim2
        persistentVolumeClaim:
          claimName: traefik-claim2
status: {}
