apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: watchtower
  name: watchtower
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: watchtower
    spec:
      containers:
      - args:
        - --schedule
        - 0 0 4 * * *
        - --cleanup
        image: v2tec/watchtower
        name: watchtower
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: watchtower-claim0
      restartPolicy: Always
      volumes:
      - name: watchtower-claim0
        persistentVolumeClaim:
          claimName: watchtower-claim0
status: {}
